JPERF-903 Open NotificationPopUps class to make it accessible from other JPT related libraries
atlassian/jira-actions pull request #112
Opened 2022-12-13 13:16 UTC by ewefie

To fix the flakiness of `edit sprint` action defined in `jira-software-actions` module I needed a way to close AUI flags. The mechanism for that was already implemented in this module however, `NotificationPopUps` was defined as an internal class. To make it possible to use this class in `jira-software-action` and avoid code duplication I removed that modifier.

2022-12-13 13:23 UTC, mgrzaslewicz submitted a review, later dismissed

2022-12-13 14:28 UTC, dagguh requested changes

2022-12-13 14:28 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/jiraactions/page/NotificationPopUps.kt
> -internal class NotificationPopUps(private val driver: WebDriver) {
According to the `CHANGELOG.md`, it also needs to be in the `api` subpackage

2022-12-14 07:43 UTC, mgrzaslewicz approved these changes

2022-12-14 08:42 UTC, dagguh approved these changes

2022-12-14 08:45 UTC, dagguh commented
CI flaked for 7.13.0.
PS. Imagine having monorepo, and having to test `jira-software-actions`, `aws-infrastructure` and all other CIs. The combined flakiness, the duration, the combinations of test parameters like Jira versions.

2022-12-14 09:52 UTC, merged