Mark 3.22.0 release
atlassian/jira-actions pull request #152
Opened 2023-09-14 18:09 UTC by mgrzaslewicz

2023-09-14 18:12 UTC, dagguh submitted a review, later dismissed

2023-09-14 18:17 UTC, pczuj commented on CHANGELOG.md
> +[3.22.0]: https://github.com/atlassian/jira-actions/compare/release-3.21.1...release-3.22.0
```suggestion
[3.22.0]: https://github.com/atlassian/jira-actions/compare/release-3.21.2...release-3.22.0
```

2023-09-14 18:17 UTC, pczuj requested changes
typo in version range

2023-09-14 18:31 UTC, dagguh approved these changes

2023-09-15 06:23 UTC, pczuj approved these changes

2023-09-15 06:23 UTC, merged